# The Netflix Data
https://www.kaggle.com/datasets/shivamb/netflix-shows

##### Objective: data will be imported into Juypyter Notebook using the Kaggle API. The data will be dynamically written to a MySQL Database. From there the data will be cleaned using SQL

In [26]:
import kaggle
import pandas as pd
import zipfile as zf

In [28]:
## Download the Kaggle Dataset to the root directory
!kaggle datasets download shivamb/netflix-shows -f netflix_titles.csv

Dataset URL: https://www.kaggle.com/datasets/shivamb/netflix-shows
License(s): CC0-1.0
Downloading netflix_titles.csv.zip to C:\Users\dyolf\netflix

  0%|          | 0.00/1.34M [00:00<?, ?B/s]
100%|##########| 1.34M/1.34M [00:00<00:00, 16.7MB/s]

In [30]:
# Extract the CSV from the zipfile
import zipfile
file = r"C:\Users\dyolf\netflix\netflix_titles.csv.zip"
with zipfile.ZipFile(file, mode='r', \
                     allowZip64=True, \
                     compresslevel=None, \
                     strict_timestamps=True,\
                     metadata_encoding=None) as zipref:
    with zipref.open('netflix_titles.csv', mode = 'r') as f:
        df = pd.read_csv(f, na_values = ['Not Available', 'unknown'])

In [32]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [80]:
# write the data to a MySQL Database
import sqlalchemy as sal

In [82]:
url_object = sal.URL.create(
    drivername= 'mysql+mysqlconnector',
    username= 'fbrooks',
    password= '!@lilburn007',
    host= 'localhost',
    port= 3306,
    database= 'floyd'
)

In [84]:
engine = sal.create_engine(url_object, echo = True)

In [94]:
try:
    with engine.connect() as conn:
        df.to_sql(name= 'netflix_raw', con = conn, index = False, if_exists = 'replace')
        print("DataFrame written to SQL table successfully.")

         # Print DataFrame details for verification
        # print(f"DataFrame shape: {df.shape}")
        # print(df.head())
except Exception as e:
    print(f'There was a problem: {e}')
    pass

2024-07-27 03:26:53,712 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-27 03:26:53,718 INFO sqlalchemy.engine.Engine DESCRIBE `floyd`.`netflix_raw`
2024-07-27 03:26:53,719 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-07-27 03:26:53,722 INFO sqlalchemy.engine.Engine DESCRIBE `floyd`.`netflix_raw`
2024-07-27 03:26:53,722 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-07-27 03:26:53,724 INFO sqlalchemy.engine.Engine SHOW FULL TABLES FROM `floyd`
2024-07-27 03:26:53,725 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-07-27 03:26:53,727 INFO sqlalchemy.engine.Engine SHOW FULL TABLES FROM `floyd`
2024-07-27 03:26:53,727 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-07-27 03:26:53,729 INFO sqlalchemy.engine.Engine SHOW CREATE TABLE `netflix_raw`
2024-07-27 03:26:53,731 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-07-27 03:26:53,733 INFO sqlalchemy.engine.Engine
DROP TABLE netflix_raw
2024-07-27 03:26:53,734 INFO sqlalchemy.engine.Engine [no key 0.00078s] {}
2024-07-27 03:26:53,744 INFO sqlalchemy.engine.Engine
CREATE TABLE netflix_raw (
	show_id TEXT,
	type TEXT,
	title TEXT,
	director TEXT,
	cast TEXT,
	country TEXT,
	date_added TEXT,
	release_year BIGINT,
	rating TEXT,
	duration TEXT,
	listed_in TEXT,
	description TEXT
)


2024-07-27 03:26:53,744 INFO sqlalchemy.engine.Engine [no key 0.00091s] {}
2024-07-27 03:26:53,833 INFO sqlalchemy.engine.Engine INSERT INTO netflix_raw (show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description) VALUES (%(show_id)s, %(type)s, %(title)s, %(director)s, %(cast)s, %(country)s, %(date_added)s, %(release_year)s, %(rating)s, %(duration)s, %(listed_in)s, %(description)s)
2024-07-27 03:26:53,834 INFO sqlalchemy.engine.Engine [generated in 0.05482s] [{'show_id': 's1', 'type': 'Movie', 'title': 'Dick Johnson Is Dead', 'director': 'Kirsten Johnson', 'cast': None, 'country': 'United States', 'date_added': 'September 25, 2021', 'release_year': 2020, 'rating': 'PG-13', 'duration': '90 min', 'listed_in': 'Documentaries', 'description': 'As her father nears the end of his life, filmmaker Kirsten Johnson stages his death in inventive and comical ways to help them both face the inevitable.'}, {'show_id': 's2', 'type': 'TV Show', 'title': 'Blood & Water', 'director': None, 'cast': 'Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mah ... (5 characters truncated) ... , Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng', 'country': 'South Africa', 'date_added': 'September 24, 2021', 'release_year': 2021, 'rating': 'TV-MA', 'duration': '2 Seasons', 'listed_in': 'International TV Shows, TV Dramas, TV Mysteries', 'description': 'After crossing paths at a party, a Cape Town teen sets out to prove whether a private-school swimming star is her sister who was abducted at birth.'}, {'show_id': 's3', 'type': 'TV Show', 'title': 'Ganglands', 'director': 'Julien Leclercq', 'cast': 'Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera', 'country': None, 'date_added': 'September 24, 2021', 'release_year': 2021, 'rating': 'TV-MA', 'duration': '1 Season', 'listed_in': 'Crime TV Shows, International TV Shows, TV Action & Adventure', 'description': 'To protect his family from a powerful drug lord, skilled thief Mehdi and his expert team of robbers are pulled into a violent and deadly turf war.'}, {'show_id': 's4', 'type': 'TV Show', 'title': 'Jailbirds New Orleans', 'director': None, 'cast': None, 'country': None, 'date_added': 'September 24, 2021', 'release_year': 2021, 'rating': 'TV-MA', 'duration': '1 Season', 'listed_in': 'Docuseries, Reality TV', 'description': 'Feuds, flirtations and toilet talk go down among the incarcerated women at the Orleans Justice Center in New Orleans on this gritty reality series.'}, {'show_id': 's5', 'type': 'TV Show', 'title': 'Kota Factory', 'director': None, 'cast': 'Mayur More, Jitendra Kumar, Ranjan Raj, Alam Khan, Ahsaas Channa, Revathi Pillai, Urvi Singh, Arun Kumar', 'country': 'India', 'date_added': 'September 24, 2021', 'release_year': 2021, 'rating': 'TV-MA', 'duration': '2 Seasons', 'listed_in': 'International TV Shows, Romantic TV Shows, TV Comedies', 'description': 'In a city of coaching centers known to train India’s finest collegiate minds, an earnest but unexceptional student and his friends navigate campus life.'}, {'show_id': 's6', 'type': 'TV Show', 'title': 'Midnight Mass', 'director': 'Mike Flanagan', 'cast': 'Kate Siegel, Zach Gilford, Hamish Linklater, Henry Thomas, Kristin Lehman, Samantha Sloyan, Igby Rigney, Rahul Kohli, Annarah Cymone, Annabeth Gish, Alex Essoe, Rahul Abburi, Matt Biedel, Michael Trucco, Crystal Balint, Louis Oliver', 'country': None, 'date_added': 'September 24, 2021', 'release_year': 2021, 'rating': 'TV-MA', 'duration': '1 Season', 'listed_in': 'TV Dramas, TV Horror, TV Mysteries', 'description': 'The arrival of a charismatic young priest brings glorious miracles, ominous mysteries and renewed religious fervor to a dying town desperate to believe.'}, {'show_id': 's7', 'type': 'Movie', 'title': 'My Little Pony: A New Generation', 'director': 'Robert Cullen, José Luis Ucha', 'cast': 'Vanessa Hudgens, Kimiko Glenn, James Marsden, Sofia Carson, Liza Koshy, Ken Jeong, Elizabeth Perkins, Jane Krakowski, Michael McKean, Phil LaMarr', 'country': None, 'date_added': 'September 24, 2021', 'release_year': 2021, 'rating': 'PG', 'duration': '91 min', 'listed_in': 'Children & Family Movies', 'description': "Equestria's divided. But a bright-eyed hero believes Earth Ponies, Pegasi and Unicorns should be pals — and, hoof to heart, she’s determined to prove it."}, {'show_id': 's8', 'type': 'Movie', 'title': 'Sankofa', 'director': 'Haile Gerima', 'cast': 'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri', 'country': 'United States, Ghana, Burkina Faso, United Kingdom, Germany, Ethiopia', 'date_added': 'September 24, 2021', 'release_year': 1993, 'rating': 'TV-MA', 'duration': '125 min', 'listed_in': 'Dramas, Independent Movies, International Movies', 'description': 'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.'}  ... displaying 10 of 8807 total bound parameter sets ...  {'show_id': 's8806', 'type': 'Movie', 'title': 'Zoom', 'director': 'Peter Hewitt', 'cast': 'Tim Allen, Courteney Cox, Chevy Chase, Kate Mara, Ryan Newman, Michael Cassidy, Spencer Breslin, Rip Torn, Kevin Zegers', 'country': 'United States', 'date_added': 'January 11, 2020', 'release_year': 2006, 'rating': 'PG', 'duration': '88 min', 'listed_in': 'Children & Family Movies, Comedies', 'description': 'Dragged from civilian life, a former superhero must train a new crop of youthful saviors when the military preps for an attack by a familiar villain.'}, {'show_id': 's8807', 'type': 'Movie', 'title': 'Zubaan', 'director': 'Mozez Singh', 'cast': 'Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanana, Manish Chaudhary, Meghna Malik, Malkeet Rauni, Anita Shabdish, Chittaranjan Tripathy', 'country': 'India', 'date_added': 'March 2, 2019', 'release_year': 2015, 'rating': 'TV-14', 'duration': '111 min', 'listed_in': 'Dramas, International Movies, Music & Musicals', 'description': "A scrappy but poor boy worms his way into a tycoon's dysfunctional family, while facing his fear of music and the truth about his past."}]
2024-07-27 03:26:54,183 INFO sqlalchemy.engine.Engine COMMIT
DataFrame written to SQL table successfully.

In [88]:
# count rows and columns in df

In [90]:
df.shape

(8807, 12)

In [96]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [92]:
df.query("show_id == 's5023'")

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5022,s5023,Movie,반드시 잡는다,Hong-seon Kim,Baek Yoon-sik,South Korea,"February 28, 2018",2017,TV-MA,110 min,"Dramas, International Movies, Thrillers",After people in his town start turning up dead...

In [56]:
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [ ]:
# Find the Maximum length of data in each column to optimize performance in SQL

In [76]:
df['cast'].str.len().max()

771.0

In [78]:
df['country'].str.len().max()

123.0

In [146]:
# Split the columns but handle nan values
df['director'] = df['director'].fillna('')

In [192]:
directors = df['director'].apply(lambda x: len(x.split(',')) if x else 0)
max_count_row = df.loc[directors.idxmax()]
max_count_row
df.query("show_id == 's5888'")

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5887,s5888,Movie,Walt Disney Animation Studios Short Films Coll...,"Chris Buck, Jennifer Lee, Patrick Osborne, Lau...","Kristen Bell, Josh Gad, Jonathan Groff, Idina ...",United States,"October 25, 2015",2015,TV-Y,90 min,Children & Family Movies,This collection of 12 short films from Disney ...

In [198]:
# Access and print the content of a specific cell
cell_content = df.loc[224, 'director']
print(cell_content)